/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import service.InventoryService;

/**
 *
 * @author Nibal
 */
public class Login extends javax.swing.JFrame {
InventoryService service;
    /**
     * Creates new form Login
     */
    public Login(InventoryService service) {
        this.service=service;
        initComponents();
    }
    public Login(){
          initComponents();
    
    }
    String ManagerToken="123456";
    boolean readManagerAccount(String email, String password) {
        boolean o = false;

        try (BufferedReader reader = new BufferedReader(new FileReader("newManagerAccount.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");  

                if (parts.length < 2) {
                    continue;  
                }

                String n = parts[0].trim();
                String p = parts[1].trim();

                if (email.equals(n) && password.equals(p)) {
                   
                    o = true;

                }
      
            }

            if (!o) {
                JOptionPane.showMessageDialog(null, "email or password is not corect   ");
            } else {
                this.setVisible(false);
                new Manager(service).setVisible(true);

            }

            return true;  // Successfully read the file
        } catch (IOException e) {
            e.printStackTrace();
            return false;  // Error occurred while reading the file
        }

    }

    public boolean readProductionSuperiorAccount(String email,String password){
        String line;
        boolean o = false;
        try(BufferedReader reader=new BufferedReader(new FileReader("newProductionAccount.txt") )){
            while((line=reader.readLine())!=null){
              String[] parts = line.split(",");
              if(parts.length<2){
              continue;
              }
            String p= parts[0].trim();
            String c= parts[1].trim();
            if(email.equals(p)&&password.equals(c)){
               
               
            o=true;
            }
            }
            if (!o) {
                JOptionPane.showMessageDialog(null, "email or password is not corect   ");
            } else {
                this.setVisible(false);
                new ProductionSuperior(service).setVisible(true);

            }

            
               return true;
            
        }catch(IOException e){
        e.printStackTrace();
        return false;
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 6, 150, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, 130, 100));

        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, 280, 30));
        jTextField1.getAccessibleContext().setAccessibleName("Email");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 202, 130, 30));

        jPasswordField1.setText("12345");
        jPasswordField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        panel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 30));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Production Supervisor");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        panel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 170, 30));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Manager");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        panel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Login");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 80, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Create new account?");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nibal\\Documents\\NetBeansProjects\\PIMS\\src\\main\\image\\photo_2025-12-05_23-57-49.jpg")); // NOI18N
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 330, 440));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 330, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nibal\\Documents\\NetBeansProjects\\PIMS\\src\\main\\image\\Gemini_Generated_Image_dwmyr0dwmyr0dwmy - Copy.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1030, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
  jCheckBox1.setSelected(true);
  jCheckBox2.setSelected(false);
  
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String email=jTextField1.getText();
           String password=jPasswordField1.getText();
          
if(  jCheckBox1.isSelected()){
readProductionSuperiorAccount(email,password);
}
else if( jCheckBox2.isSelected()){
readManagerAccount(email,password);

}
else {
    JOptionPane.showMessageDialog(null, "Select your role  ");
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
  jCheckBox1.setSelected(false);
  jCheckBox2.setSelected(true);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new Signup(service).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
       
       
         

  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
  
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
