/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import ui.Login;
import ui.ProductionSuperior;
import ui.Manager;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import service.InventoryService;

/**
 *
 * @author Nibal
 */
public class Signup extends javax.swing.JFrame {
InventoryService service;
    /**
     * Creates new form Signup
     */
    public Signup(InventoryService service) {
        this.service=service;
        initComponents();
    }
public Signup(){
 initComponents();

}
   String ManagerToken="123456";
      String ProductionToken="1234567";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        create = new javax.swing.JButton();
        loginagain = new javax.swing.JButton();
        manager = new javax.swing.JCheckBox();
        production = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Signup");
        jLabel2.setToolTipText("");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 6, 130, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Email");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 70));

        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jPasswordField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, 30));

        create.setBackground(new java.awt.Color(204, 204, 204));
        create.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        create.setText("Create");
        create.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        panel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, 30));

        loginagain.setBackground(new java.awt.Color(204, 204, 204));
        loginagain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginagain.setText("Login?");
        loginagain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginagainActionPerformed(evt);
            }
        });
        panel1.add(loginagain, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 90, 30));

        manager.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manager.setForeground(new java.awt.Color(255, 255, 255));
        manager.setText("Manager");
        manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerActionPerformed(evt);
            }
        });
        panel1.add(manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 334, 90, 30));

        production.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        production.setForeground(new java.awt.Color(255, 255, 255));
        production.setText("Production Superior");
        production.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productionActionPerformed(evt);
            }
        });
        panel1.add(production, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, 40));
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Permision Token");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, -1));
        panel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 280, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nibal\\Documents\\NetBeansProjects\\PIMS\\src\\main\\image\\photo_2025-12-05_23-57-49.jpg")); // NOI18N
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 989, 863));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 330, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nibal\\Documents\\NetBeansProjects\\PIMS\\src\\main\\image\\Gemini_Generated_Image_dwmyr0dwmyr0dwmy - Copy.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1150, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginagainActionPerformed
       this.setVisible(false);
       new Login(service).setVisible(true);
    }//GEN-LAST:event_loginagainActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        String email =   jTextField1.getText();
    String password = new String(jPasswordField1.getPassword());
    
    if (jTextField1.getText().length()!=0&&jPasswordField1.getText().length()!=0){
         if(manager.isSelected() && jTextField2.getText().equals(ManagerToken)){
     
           
            try {
            FileWriter fw;
            fw = new FileWriter("newManagerAccount.txt", true);
            PrintWriter pw = new PrintWriter(fw, true);
            pw.println( email + "," + password );

        } catch (IOException ex) {
           
        }

           
       
        this.setVisible(false);
       new Manager(service).setVisible(true);

        
         }

         
         
         else if(production.isSelected() && jTextField2.getText().equals(ProductionToken)){
     try {
            FileWriter fw;
            fw = new FileWriter("newProductionAccount.txt", true);
            PrintWriter pw = new PrintWriter(fw, true);
            pw.println( email + "," + password );

        } catch (IOException ex) {
           
        }
     

       
              this.setVisible(false);
       new ProductionSuperior(service).setVisible(true);
         }
        
         
    
   
    }
    else {
    JOptionPane.showMessageDialog(null, "Sorry filed is not full");
    }

 
    }//GEN-LAST:event_createActionPerformed

    private void managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerActionPerformed
    manager.setSelected(true);
    production.setSelected(false);
    }//GEN-LAST:event_managerActionPerformed

    private void productionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productionActionPerformed
  manager.setSelected(false);
    production.setSelected(true);
    }//GEN-LAST:event_productionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
             
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loginagain;
    private javax.swing.JCheckBox manager;
    private java.awt.Panel panel1;
    private javax.swing.JCheckBox production;
    // End of variables declaration//GEN-END:variables
}
